### ISSUE TITLE
Make it java 8 compatible

### ISSUE THREAD

**Issue by vtkstef** [f4b6a3/ulid-creator#1]
are you using any post java 8 features that make it hard to support java 8?

**Comment by fabiolimace** [comment]
No. I'll downgrade to java 8 in the next weekend.

**Comment by fabiolimace** [comment]
Now it is java 8 compatible. The version 2.0.0 will be available on maven central in the next hours.

Commit: 327aa7bc6b4de718a54108e8c40650223581f431.

I'll close this issue, ok? Thank you!
